# mongo
DEFAULT_MONGO_SERVICE_NAME = "mongo-db"
DEFAULT_MONGO_IMAGE = "mongo:6.0.5"
DEFAULT_MONGO_ROOT_USER = "root"
DEFAULT_MONGO_ROOT_PASSWORD = "password"
DEFAULT_BACKEND_DB_NAME = "backend-db"
DEFAULT_BACKEND_DB_USER = "backend"
DEFAULT_BACKEND_DB_PASSWORD = "backend"

# backend service
DEFAULT_BACKEND_HTTP_PUBLIC_PORT = 65535
