services:
  mongo:
    image: mongo:6.0.5
    ports:
      - :27017
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    # starts the daemon and create the backend's database and user  
    command: ["/bin/bash", "-c", "mongod && sleep 5 && mongosh -u root -p password -eval \"db.getSiblingDB('backend-db').createUser({user:'backend', pwd:'backend', roles:[{role:'readWrite',db:'backend-db'}]});\""] 
    healthcheck:
      test: ["CMD-SHELL", "echo just wait || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    image: node:16.14.2
    ports:
      - 8080:8080
    volumes:
      - ./backend/files:/server/files
    environment:
      - MONGO_URI=mongodb://backend:backend@mongo:27017/backend-db
    command: ["/bin/bash", "-c", "cd /server/files/ && npm i && npm start"]
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    image: node:16.14.2
    ports:
      - 3000:3000
    volumes:
      - ./frontend/files:/frontend/files
    environment:
      - WDS_SOCKET_PORT=0
    command: ["/bin/bash", "-c", "cd /frontend/files/ && npm i && npm run build && npm install -g serve && serve -s build"]

volumes:
  mongo-data:
