services:
  mongo:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    #restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      #- MONGO_INITDB_DATABASE=backend-db
    # starts the daemon and create the backend's database and user  
    #command: ["mongod"] 
    # healthcheck:
      # test: ["CMD-SHELL", "mongosh mongodb://backend:backend@localhost:27017/backend-db  || exit 1"]
      # interval: 10m
      # timeout: 10s
      # retries: 3
      # start_period: 10s

  backend:
    image: node:16.14.2
    ports:
      - 8080:8080
    volumes:
      - ./backend/files:/server/files
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/backend-db
    command: ["/bin/bash", "-c", "cd /server/files/ && npm i && npm start"]
    depends_on:
      - mongo
        # condition: service_healthy


  frontend:
    image: node:16.14.2
    ports:
      - 3000:3000
    volumes:
      - ./frontend/files:/frontend/files
    environment:
      - WDS_SOCKET_PORT=0
    command: ["/bin/bash", "-c", "cd /frontend/files/ && npm i && npm run build && npm install -g serve && serve -s build"]

volumes:
  mongo-data:
