services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    #volumes:
      #- mongo-data:/data/db

  backend:
    image: node:16.14.2
    ports:
      - 8080:8080
    volumes:
      - ./backend/files:/server/files
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
    command: ["/bin/bash", "-c", "cd /server/files/ && npm i && npm start"]
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:8080"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 3s

  frontend:
    image: kurtosistech/mern-package-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=0
    command: ["/bin/bash", "-c", "cd /frontend/files/ && serve -s build"]
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s

  gateway:
    image: nginx:latest
    ports:
      - :80
    volumes:
      - ./gateway/docker-compose-templates:/etc/nginx/templates
    environment:
      - NGINX_PORT_NUMBER=80
      - NGINX_ROOT_FOLDER=/var/www/html
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    depends_on:
      frontend:
        condition: service_healthy

#volumes:
  #mongo-data:
    #driver: local