const ORIGIN = '*'
const PORT = process.env.PORT || 8080

// it will be filled with the generated by Kurtosis Mongo URI
const MONGO_URI = '{{.MongoURI}}'
const MONGO_OPTIONS = {}

const JWT_SECRET = process.env.JWT_SECRET || 'unsafe_secret'

module.exports = {
  ORIGIN,
  PORT,
  MONGO_URI,
  MONGO_OPTIONS,
  JWT_SECRET,
}
